[package]
name = "keyvalint"
version = "0.1.0"
edition = "2021"

[features]
default = ["reference"]

reference = []
rocksdb = ["dep:rocksdb"]

[dependencies]
rocksdb = { version = "0.21", optional = true }
