[package]
name = "tatl"
version = "0.8.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "tatl provides in-process alerting."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[dependencies]
biometrics = { path = "../biometrics", version = "0.9" }
one_two_eight = { path = "../one_two_eight", version = "0.6" }
prototk = { path = "../prototk", version = "0.10" }
