[package]
name = "tatl"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"

[dependencies]
rand = "0.7"

biometrics = { path = "../biometrics", version = "0.1.1" }
one_two_eight = { path = "../one_two_eight", version = "0.1.0" }
indicio = { path = "../indicio" }
prototk = { path = "../prototk", version = "0.2" }
