[package]
name = "tatl"
version = "0.2.1"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "tatl provides in-process alerting."
license = "Apache-2.0"

[dependencies]
rand = "0.7"

biometrics = { path = "../biometrics", version = "0.3" }
one_two_eight = { path = "../one_two_eight", version = "0.2" }
prototk = { path = "../prototk", version = "0.2" }
