[package]
name = "prototk"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"

[dependencies]
buffertk = { path = "../buffertk", version = "0.1.0" }
prototk_derive = { path = "../prototk_derive", version = "0.1.0" }
zerror = { path = "../zerror", version = "0.1.0" }
