[package]
name = "prototk"
version = "0.11.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "prototk provides a toolkit for prototcol buffers."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[dependencies]
buffertk = { path = "../buffertk", version = "0.12" }
prototk_derive = { path = "../prototk_derive", version = "0.12" }
zerror = { path = "../zerror", version = "0.7" }
