[package]
name = "macarunes"
version = "0.2.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Macarunes provides an implementation of macaroons."
license = "Apache-2.0"

[dependencies]
rand = "0.7"
libsodium-sys-stable = "1.19"

biometrics = { path = "../biometrics", version = "0.4" }
buffertk = { path = "../buffertk", version = "0.5" }
prototk = { path = "../prototk", version = "0.4" }
prototk_derive = { path = "../prototk_derive", version = "0.5" }
