[package]
name = "macarunes"
version = "0.3.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Macarunes provides an implementation of macaroons."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[dependencies]
libsodium-sys-stable = "1.19"

biometrics = { path = "../biometrics", version = "0.8" }
buffertk = { path = "../buffertk", version = "0.8" }
prototk = { path = "../prototk", version = "0.8" }
prototk_derive = { path = "../prototk_derive", version = "0.8" }
