[package]
name = "macarunes"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Macarunes provides an implementation of macaroons."
license = "Apache-2.0"

[dependencies]
getopts = "0.2"
rand = "0.7"
libsodium-sys-stable = "1.19"

arrrg = { path = "../arrrg", version = "0.1" }
arrrg_derive = { path = "../arrrg_derive", version = "0.1" }
biometrics = { path = "../biometrics", version = "0.3" }
buffertk = { path = "../buffertk", version = "0.3" }
prototk = { path = "../prototk", version = "0.2" }
prototk_derive = { path = "../prototk_derive", version = "0.3" }
