[package]
name = "split_channel"
version = "0.13.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "split_channel provides a stream-of-messages abstraction with split send/recv channels."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[features]
default = ["binaries"]

binaries = ["command_line"]
command_line = ["dep:arrrg", "dep:arrrg_derive", "dep:getopts"]

[dependencies]
libc = "0.2"
boring = "4.7.0"
crc32c = "0.6"

biometrics = { path = "../biometrics", version = "0.11" }
buffertk = { path = "../buffertk", version = "0.12" }
prototk = { path = "../prototk", version = "0.12" }
prototk_derive = { path = "../prototk_derive", version = "0.12" }
rpc_pb = { path = "../rpc_pb", version = "0.13" }
utilz = { path = "../utilz", version = "0.7" }
zerror = { path = "../zerror", version = "0.8" }
zerror_core = { path = "../zerror_core", version = "0.12" }

getopts = { version = "0.2", optional = true }
arrrg = { path = "../arrrg", version = "0.7", optional = true }
arrrg_derive = { path = "../arrrg_derive", version = "0.8", optional = true }

[[example]]
name = "split_channel-benchmark-client"
path = "examples/split_channel-benchmark-client.rs"
required-features=["binaries"]

[[example]]
name = "split_channel-benchmark-server"
path = "examples/split_channel-benchmark-server.rs"
required-features=["binaries"]
