[package]
name = "rustrc"
version = "0.5.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "rustrc is an rc-inspired init system as a library"
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[features]
default = ["binaries"]

binaries = []

[dependencies]
libc = "0.2"
getopts = { version = "0.2" }

arrrg = { path = "../arrrg", version = "0.4" }
arrrg_derive = { path = "../arrrg_derive", version = "0.4" }
biometrics = { path = "../biometrics", version = "0.8" }
indicio = { path = "../indicio", version = "0.6" }
minimal_signals = { path = "../minimal_signals", version = "0.3" }
one_two_eight = { path = "../one_two_eight", version = "0.5" }
rc_conf = { path = "../rc_conf", version = "0.6" }
shvar = { path = "../shvar", version = "0.5" }
unix_sock = { path = "../unix_sock", version = "0.6" }
utf8path = { path = "../utf8path", version = "0.5" }

[[bin]]
name = "rustrc"
path = "src/bin/rustrc.rs"
required-features=["binaries"]

[[bin]]
name = "rustrc-smoke-test"
path = "src/bin/rustrc-smoke-test.rs"
required-features=["binaries"]
