[package]
name = "rivulet"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Rivulet provides a stream-of-messages abstraction."
license = "Apache-2.0"

[dependencies]
libc = "0.2"
getopts = "0.2"
boring = "2.1.0"
crc32c = "0.6"

arrrg = { path = "../arrrg", version = "0.1" }
arrrg_derive = { path = "../arrrg_derive", version = "0.1" }
biometrics = { path = "../biometrics", version = "0.2" }
buffertk = { path = "../buffertk", version = "0.2" }
prototk = { path = "../prototk", version = "0.2" }
prototk_derive = { path = "../prototk_derive", version = "0.2" }
rpc_pb = { path = "../rpc_pb", version = "0.1" }
utilz = { path = "../utilz", version = "0.1" }
zerror = { path = "../zerror", version = "0.1" }
zerror_core = { path = "../zerror_core", version = "0.2" }
