[workspace]
members = [
    "armnod",
    "biometrics",
    "bloom",
    "buffertk",
    "busybee",
    "cache",
    "ci",
    "clue",
    "databuf",
    "derive_util",
    "guacamole",
    "hey_listen",
    "id",
    "lp",
    "prototk",
    "prototk_derive",
    "setsum",
    "tiny_lfu",
    "tuple_key",
    "tuple_key_derive",
    "util",
    "zerror",
    "zerror_core",
]

[profile.release]
debug = true
