[workspace]
members = [
    "armnod",
    "biometrics",
    "bloom",
    "buffertk",
    "clue",
    "databuf",
    "guacamole",
    "hey_listen",
    "id",
    "lp",
    "prototk",
    "prototk_derive",
    "setsum",
    "sim",
    "util",
    "zerror",
]

[profile.release]
debug = true
