[workspace]
resolver = "2"
members = [
    "armnod",
    "arrrg",
    "arrrg_derive",
    "biometrics",
    "biometrics_pb",
    "bloomcalc",
    "buffertk",
    "busyrpc",
    "derive_util",
    "guacamole",
    "indicio",
    "keyvalint",
    "keyvalint_bench",
    "lsmtk",
    "macarunes",
    "mani",
    "meta",
    "one_two_eight",
    "paxos_pb",
    "prototk",
    "prototk_derive",
    "rpc_pb",
    "scrunch",
    "setsum",
    "skipfree",
    "split_channel",
    "sst",
    "sync42",
    "tatl",
    "texttale",
    "tiny_lfu",
    "tuple_db",
    "tuple_key",
    "tuple_key_derive",
    "utilz",
    "zerror",
    "zerror_derive",
    "zerror_core",
]

# Scrunch is under progress on a separate branch.  As-is it's unusable.
exclude = [
    "scrunch",
]

[profile.release]
debug = true
lto = true
