[workspace]
members = [
    "armnod",
    "arrrg",
    "arrrg_derive",
    "biometrics",
    "biometrics_pb",
    "bloom",
    "buffertk",
    "busybee",
    "cache",
    "ci",
    "databuf",
    "derive_util",
    "guacamole",
    "hey_listen",
    "indicio",
    "lp",
    "one_two_eight",
    "prototk",
    "prototk_derive",
    "rivulet",
    "setsum",
    "sst",
    "sync42",
    "texttale",
    "tiny_lfu",
    "tuple_key",
    "tuple_key_derive",
    "util",
    "zerror",
    "zerror_core",
]

[profile.release]
debug = true
