#!/bin/bash

set -x
set -u
set -o errexit
set -o pipefail

cargo fmt -- --check

ROOTDIR="`pwd`"
export PATH="$PATH":"`pwd`"/target/release
# TODO(rescrv, 1.91):  Remove this allowance.
export RUSTFLAGS="-A clippy::needless-lifetimes --deny warnings"

cargo build --release --bins
target/release/publish > .ci.packages

for package in `cat .ci.packages`
do
    pushd $package
    cargo clippy --no-deps --all-targets
    cargo hack --feature-powerset test --release
    cargo doc --no-deps
    "${ROOTDIR}/target/release/binaries"
    popd
done

set +x
echo SUCCESS: this concludes our successful CI adventure
