#!/bin/zsh

set -e
set -x

cargo fmt -- --check

ROOTDIR="`pwd`"
export PATH="$PATH":"`pwd`"/target/release
# TODO(rescrv, 1.91):  Remove this allowance.
export RUSTFLAGS="-A clippy::needless-lifetimes --deny warnings"

cargo build --release --bins

for package in `target/release/publish`
do
    pushd $package
    cargo clippy --no-deps --all-targets
    cargo hack $HACK_FLAGS --feature-powerset test --release
    cargo doc --no-deps
    "${ROOTDIR}/target/release/binaries"
    popd
done

set +x
echo SUCCESS: this concludes our successful CI adventure
