#!/usr/bin/env zsh

set -e
set -x

PACKAGE=$1
shift

FROM_VER=$1
shift

TO_VER=$1
shift

sed -i -e 's|'$PACKAGE' = { path = "../'$PACKAGE'", version = "'$FROM_VER'"|'$PACKAGE' = { path = "../'$PACKAGE'", version = "'$TO_VER'"|g' */Cargo.toml
cargo check --all-targets
