#!/usr/bin/env zsh

set -e
set -x

PACKAGE=$1
shift

FROM_VER=$1
shift

FROM_SHORT_VER=$1
shift

TO_VER=$1
shift

TO_SHORT_VER=$1
shift

sed -i -e 's|version = "'$FROM_VER'"|version = "'$TO_VER'"|g' $PACKAGE/Cargo.toml
sed -i -e 's|'$PACKAGE' = { path = "../'$PACKAGE'", version = "'$FROM_SHORT_VER'"|'$PACKAGE' = { path = "../'$PACKAGE'", version = "'$TO_SHORT_VER'"|g' */Cargo.toml
cargo check --all-targets
