[package]
name = "rpc"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"

[dependencies]
biometrics = { path = "../biometrics" }
buffertk = { path = "../buffertk" }
error_core = { path = "../error_core" }
guacamole = { path = "../guacamole" }
hey_listen = { path = "../hey_listen" }
id = { path = "../id" }
prototk = { path = "../prototk" }
prototk_derive = { path = "../prototk_derive" }
util = { path = "../util" }
zerror = { path = "../zerror" }
