[package]
name = "lsmtk"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "lsmtk provides a log-structured-merge-graph"
license = "Apache-2.0"

[dependencies]
getopts = "0.2"

arrrg = { path = "../arrrg", version = "0.2" }
arrrg_derive = { path = "../arrrg_derive", version = "0.2" }
biometrics = { path = "../biometrics", version = "0.3" }
buffertk = { path = "../buffertk", version = "0.4" }
mani = { path = "../mani", version = "0.1" }
prototk = { path = "../prototk", version = "0.3" }
prototk_derive = { path = "../prototk_derive", version = "0.3" }
setsum = { path = "../setsum", version = "0.3" }
sst = { path = "../sst", version = "0.3" }
zerror = { path = "../zerror", version = "0.1" }
zerror_core = { path = "../zerror_core", version = "0.2" }
zerror_derive = { path = "../zerror_derive", version = "0.1" }
