[package]
name = "symphonize"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "symphonize is a tool for running integration tests across services"
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[features]
default = ["binaries"]

binaries = []

[dependencies]
libc = "0.2"
getopts = { version = "0.2" }
rustyline = "11.0"

arrrg = { path = "../arrrg", version = "0.3" }
arrrg_derive = { path = "../arrrg_derive", version = "0.3" }
indicio = { path = "../indicio", version = "0.3" }
minimal_signals = { path = "../minimal_signals", version = "0.1" }
one_two_eight = { path = "../one_two_eight", version = "0.4" }
rc_conf = { path = "../rc_conf", version = "0.1" }
rustrc = { path = "../rustrc", version = "0.1" }
shvar = { path = "../shvar", version = "0.1" }
unix_sock = { path = "../unix_sock", version = "0.1" }
utf8path = { path = "../utf8path", version = "0.1" }

[[bin]]
name = "symphonize"
path = "src/bin/symphonize.rs"
required-features=["binaries"]
