[package]
name = "symphonize"
version = "0.10.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "symphonize is a tool for running integration tests across services"
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[features]
default = ["binaries"]

binaries = []

[dependencies]
getopts = { version = "0.2" }

arrrg = { path = "../arrrg", version = "0.6" }
arrrg_derive = { path = "../arrrg_derive", version = "0.6" }
indicio = { path = "../indicio", version = "0.10" }
k8src = { path = "../k8src", version = "0.10" }
rc_conf = { path = "../rc_conf", version = "0.10" }
shvar = { path = "../shvar", version = "0.6" }
utf8path = { path = "../utf8path", version = "0.6" }

[[bin]]
name = "symphonize"
path = "src/bin/symphonize.rs"
required-features=["binaries"]
