[package]
name = "guacamole"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Guacamole provides a linearly-seekable random number generator."
license = "Apache-2.0"

[dependencies]
clap = "2.33"
rand = "0.7"
