[package]
name = "guacamole"
version = "0.2.1"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Guacamole provides a linearly-seekable random number generator."
license = "Apache-2.0"

[dependencies]
getopts = "0.2"
rand = "0.7"

arrrg = { path = "../arrrg", version = "0.1" }
arrrg_derive = { path = "../arrrg_derive", version = "0.1" }
