[package]
name = "sst"
version = "0.17.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "SST provides a sorted string table abstraction."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[features]
default = ["binaries"]

binaries = ["command_line"]
command_line = ["dep:arrrg", "dep:arrrg_derive", "dep:getopts"]

[dependencies]
getopts = { version = "0.2", optional = true }
libc = "0.2"
crc32c = "0.6"
nom = "7.1"
siphasher = "1.0.0"

armnod = { path = "../armnod", version = "0.11" }
arrrg = { path = "../arrrg", version = "0.8", optional = true }
arrrg_derive = { path = "../arrrg_derive", version = "0.8", optional = true }
biometrics = { path = "../biometrics", version = "0.12" }
buffertk = { path = "../buffertk", version = "0.13" }
guacamole = { path = "../guacamole", version = "0.14" }
indicio = { path = "../indicio", version = "0.11" }
prototk_derive = { path = "../prototk_derive", version = "0.13" }
prototk = { path = "../prototk", version = "0.13" }
setsum = { path = "../setsum", version = "0.7" }
sync42 = { path = "../sync42", version = "0.15" }
tatl = { path = "../tatl", version = "0.13" }
utilz = { path = "../utilz", version = "0.7" }
zerror_core = { path = "../zerror_core", version = "0.12" }
zerror_derive = { path = "../zerror_derive", version = "0.7" }
zerror = { path = "../zerror", version = "0.8" }

[dev-dependencies]
proptest = "1.0"

[[bin]]
name = "jester-from-plaintext"
path = "src/bin/jester-from-plaintext.rs"
required-features = ["binaries"]

[[bin]]
name = "sst-stat"
path = "src/bin/sst-stat.rs"
required-features = ["binaries"]

[[bin]]
name = "sst-dump"
path = "src/bin/sst-dump.rs"
required-features = ["binaries"]

[[bin]]
name = "sst-from-log"
path = "src/bin/sst-from-log.rs"
required-features = ["binaries"]

[[bin]]
name = "log-checksum"
path = "src/bin/log-checksum.rs"
required-features = ["binaries"]

[[bin]]
name = "log-truncate-final-partial-frame"
path = "src/bin/log-truncate-final-partial-frame.rs"
required-features = ["binaries"]

[[bin]]
name = "sst-from-plaintext"
path = "src/bin/sst-from-plaintext.rs"
required-features = ["binaries"]

[[bin]]
name = "log-options"
path = "src/bin/log-options.rs"
required-features = ["binaries"]

[[bin]]
name = "sst-checksum"
path = "src/bin/sst-checksum.rs"
required-features = ["binaries"]

[[bin]]
name = "sst-options"
path = "src/bin/sst-options.rs"
required-features = ["binaries"]

[[bin]]
name = "sst-inspect"
path = "src/bin/sst-inspect.rs"
required-features = ["binaries"]

[[bin]]
name = "log-dump"
path = "src/bin/log-dump.rs"
required-features = ["binaries"]

[[bin]]
name = "log-from-plaintext"
path = "src/bin/log-from-plaintext.rs"
required-features = ["binaries"]
