[package]
name = "sst"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "SST provides a sorted string table abstraction."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
crc32c = "0.6"
rand = "0.7"

armnod = { path = "../armnod", version = "0.1.0" }
biometrics = { path = "../biometrics", version = "0.1.0" }
buffertk = { path = "../buffertk", version = "0.1.0" }
guacamole = { path = "../guacamole", version = "0.1.0" }
hey_listen = { path = "../hey_listen" }
prototk = { path = "../prototk", version = "0.1.0" }
prototk_derive = { path = "../prototk_derive", version = "0.1.0" }
setsum = { path = "../setsum", version = "0.1.0" }
util = { path = "../util" }
zerror = { path = "../zerror", version = "0.1.0" }
zerror_core = { path = "../zerror_core", version = "0.1.0" }
