[package]
name = "saros"
version = "0.2.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Saros is a terminal-based time series database."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[dependencies]
biometrics = { path = "../biometrics", version = "0.6" }
buffertk = { path = "../buffertk", version = "0.6" }
indicio = { path = "../indicio", version = "0.3" }
one_two_eight = { path = "../one_two_eight", version = "0.4" }
prototk = { path = "../prototk", version = "0.6" }
prototk_derive = { path = "../prototk_derive", version = "0.6" }
tatl = { path = "../tatl", version = "0.5" }
zerror = { path = "../zerror", version = "0.4" }
zerror_core = { path = "../zerror_core", version = "0.5" }
zerror_derive = { path = "../zerror_derive", version = "0.3" }

[[example]]
name = "saros-generate-waves"
path = "examples/saros-generate-waves.rs"
required-features=["binaries"]
