[package]
name = "saros"
version = "0.8.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Saros is a terminal-based time series database."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[features]
default = ["binaries"]

binaries = []

[dependencies]
chrono = "0.4"
getopts = "0.2"
nom = "7.1"

arrrg = { path = "../arrrg", version = "0.7" }
arrrg_derive = { path = "../arrrg_derive", version = "0.7" }
biometrics = { path = "../biometrics", version = "0.11" }
buffertk = { path = "../buffertk", version = "0.11" }
indicio = { path = "../indicio", version = "0.10" }
one_two_eight = { path = "../one_two_eight", version = "0.8" }
prototk = { path = "../prototk", version = "0.11" }
prototk_derive = { path = "../prototk_derive", version = "0.11" }
rpc_pb = { path = "../rpc_pb", version = "0.12" }
shvar = { path = "../shvar", version = "0.7" }
tag_index = { path = "../tag_index", version = "0.6" }
tatl = { path = "../tatl", version = "0.11" }
utf8path = { path = "../utf8path", version = "0.7" }
zerror = { path = "../zerror", version = "0.7" }
zerror_core = { path = "../zerror_core", version = "0.11" }
zerror_derive = { path = "../zerror_derive", version = "0.6" }

[dev-dependencies]
proptest = "1.0"

biometrics_prometheus = { path = "../biometrics_prometheus", version = "0.6" }
guacamole = { path = "../guacamole", version = "0.10" }
sig_fig_histogram = { path = "../sig_fig_histogram", version = "0.5" }

[[bin]]
name = "sarosd-recovery"
path = "src/bin/sarosd-recovery.rs"
required-features = ["binaries"]

[[bin]]
name = "saros-query-parse"
path = "src/bin/saros-query-parse.rs"
required-features = ["binaries"]

[[bin]]
name = "saros-prometheus-verify"
path = "src/bin/saros-prometheus-verify.rs"
required-features = ["binaries"]

[[example]]
name = "saros-generate-prometheus-testdata"
path = "examples/saros-generate-prometheus-testdata.rs"
required-features = ["binaries"]
