[package]
name = "tuple_key"
version = "0.4.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "A serialization format for lexicographically sorted tuples."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[dependencies]
buffertk = { path = "../buffertk", version = "0.6" }
prototk = { path = "../prototk", version = "0.6" }
prototk_derive = { path = "../prototk_derive", version = "0.6" }
tuple_key_derive = { path = "../tuple_key_derive", version = "0.5" }
zerror = { path = "../zerror", version = "0.4" }
zerror_core = { path = "../zerror_core", version = "0.4" }
zerror_derive = { path = "../zerror_derive", version = "0.3" }

[dev-dependencies]
proptest = "1.0"
