[package]
name = "tuple_key"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "A serialization format for lexicographically sorted tuples."
license = "Apache-2.0"

[dependencies]
buffertk = { path = "../buffertk", version = "0.2" }
prototk = { path = "../prototk", version = "0.1.0" }
tuple_key_derive = { path = "../tuple_key_derive" }
