[package]
name = "zerror"
version = "0.6.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "zerror provides an error interface for context-aware error-reporting."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[dependencies]
