[package]
name = "tiny_lfu"
version = "0.9.0"
edition = "2021"
description = "tiny_lfu provides a cache admission control policy."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biometrics = { path = "../biometrics", version = "0.10" }
bloomcalc = { path = "../bloomcalc", version = "0.6" }
