[package]
name = "unix_sock"
version = "0.6.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "unix_sock provides a unix control socket abstraction."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[features]
default = ["binaries"]

binaries = []

[dependencies]
libc = "0.2"

utf8path = { path = "../utf8path", version = "0.5" }

[[example]]
name = "unix-sock-client"
path = "examples/unix-sock-client.rs"
required-features=["binaries"]

[[example]]
name = "unix-sock-server"
path = "examples/unix-sock-server.rs"
required-features=["binaries"]
