[package]
name = "biometrics_pb"
version = "0.1.2"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "biometrics_pb provides protocol buffers corresponding to biometric readings."
license = "Apache-2.0"

[dependencies]
biometrics = { path = "../biometrics", version = "0.3" }
buffertk = { path = "../buffertk", version = "0.3" }
one_two_eight = { path = "../one_two_eight", version = "0.2" }
prototk = { path = "../prototk", version = "0.3" }
prototk_derive = { path = "../prototk_derive", version = "0.3" }
tuple_key = { path = "../tuple_key", version = "0.2" }
tuple_key_derive = { path = "../tuple_key_derive", version = "0.2" }
