[package]
name = "prototk_derive"
version = "0.9.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Derive macro for prototk::Message"
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"

buffertk = { path = "../buffertk", version = "0.9" }
