[package]
name = "indicio"
version = "0.1.1"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Indicio provides a framework for emitting clues that may be used for debugging."
license = "Apache-2.0"

[dependencies]
biometrics = { path = "../biometrics", version = "0.4" }
buffertk = { path = "../buffertk", version = "0.4" }
one_two_eight = { path = "../one_two_eight", version = "0.3" }
prototk = { path = "../prototk", version = "0.4" }
rpc_pb = { path = "../rpc_pb", version = "0.2" }
utilz = { path = "../utilz", version = "0.2" }
zerror = { path = "../zerror", version = "0.2" }
