[package]
name = "indicio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biometrics = { path = "../biometrics", version = "0.1.0" }
buffertk = { path = "../buffertk", version = "0.1.0" }
id = { path = "../id" }
prototk = { path = "../prototk", version = "0.1.0" }
util = { path = "../util" }
zerror = { path = "../zerror", version = "0.1.0" }
