[package]
name = "indicio"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Indicio provides a framework for emitting clues that may be used for debugging."
license = "Apache-2.0"

[dependencies]
biometrics = { path = "../biometrics", version = "0.1.1" }
buffertk = { path = "../buffertk", version = "0.2.0" }
one_two_eight = { path = "../one_two_eight" }
prototk = { path = "../prototk", version = "0.1.0" }
rpc_pb = { path = "../rpc_pb", version = "0.1.0" }
util = { path = "../util" }
zerror = { path = "../zerror", version = "0.1.0" }
