[package]
name = "zerror_full"
version = "0.6.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "zerror_full provides a macro for implementing helpful errors"
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[dependencies]
[dev-dependencies]
biometrics = { path = "../biometrics", version = "0.12" }
buffertk = { path = "../buffertk", version = "0.13" }
prototk_derive = { path = "../prototk_derive", version = "0.13" }
prototk = { path = "../prototk", version = "0.13" }
zerror_core = { path = "../zerror_core", version = "0.13" }
zerror = { path = "../zerror", version = "0.8" }
