[package]
name = "texttale"
version = "0.3.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "TextTale provides tools for writing text-mode adventures."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[features]
default = ["binaries"]

binaries = []

[dependencies]
rustyline = "11.0"

utilz = { path = "../utilz", version = "0.3" }

[[example]]
name = "texttale"
path = "examples/texttale.rs"
required-features=["binaries"]

[[example]]
name = "menu"
path = "examples/menu.rs"
required-features=["binaries"]
