[package]
name = "texttale"
version = "0.2.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "TextTale provides tools for writing text-mode adventures."
license = "Apache-2.0"

[dependencies]
rustyline = "11.0"

utilz = { path = "../utilz", version = "0.2" }
