[package]
name = "setsum"
version = "0.7.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Setsum provides an order-agnostic checksum."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[features]
default = ["binaries"]

binaries = []

[dependencies]
sha3 = "0.10"

[[bin]]
name = "setsum-calculator"
path = "src/bin/setsum-calculator.rs"
required-features = ["binaries"]
