[package]
name = "setsum"
version = "0.5.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Setsum provides an order-agnostic checksum."
license = "Apache-2.0"

[features]
default = ["binaries"]

binaries = []

[dependencies]
sha3 = "0.10"

[[bin]]
name = "setsum-inverse"
path = "src/bin/setsum-inverse.rs"
required-features = ["binaries"]
