[package]
name = "setsum"
version = "0.1.0"
authors = ["Robert Escriva <rescriva@dropbox.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9"
