[package]
name = "id"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"

[dependencies]
buffertk = { path = "../buffertk", version = "0.1.0" }
prototk = { path = "../prototk" }
