[package]
name = "sig_fig_histogram"
version = "0.2.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "sig_fig_histogram provides a histogram type that is exponentially distributed and human-friendly."
license = "Apache-2.0"


[dependencies]
