[package]
name = "shvar"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "shvar provides a POSIX-compliant shell variable substitution routine."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[dependencies]

[dev-dependencies]
proptest = "1.0"
