[package]
name = "zerror_core"
version = "0.11.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "A complete implementation of the zerror:Z trait."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[dependencies]
biometrics = { path = "../biometrics", version = "0.11" }
buffertk = { path = "../buffertk", version = "0.12" }
tatl = { path = "../tatl", version = "0.11" }
prototk = { path = "../prototk", version = "0.11" }
prototk_derive = { path = "../prototk_derive", version = "0.12" }
zerror = { path = "../zerror", version = "0.7" }
zerror_derive = { path = "../zerror_derive", version = "0.6" }
