[package]
name = "zerror_core"
version = "0.2.2"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "A complete implementation of the zerror:Z trait."
license = "Apache-2.0"

[dependencies]
biometrics = { path = "../biometrics", version = "0.3" }
buffertk = { path = "../buffertk", version = "0.3" }
tatl = { path = "../tatl", version = "0.2" }
prototk = { path = "../prototk", version = "0.3" }
prototk_derive = { path = "../prototk_derive", version = "0.3" }
zerror = { path = "../zerror", version = "0.1" }
zerror_derive = { path = "../zerror_derive", version = "0.1" }
