[package]
name = "skipfree"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "skipfree provides a lockfree skiplist"
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[dependencies]
rand = "0.7"

[dev-dependencies]
guacamole = { path = "../guacamole", version = "0.6" }
