[package]
name = "utilz"
version = "0.1.1"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "utilz provides miscellaneous utilities too small for their own crates."
license = "Apache-2.0"

[dependencies]
libc = "0.2"
