[package]
name = "zerror_derive"
version = "0.4.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "zerror_derive derives common helpers for Z crates"
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"

derive_util = { path = "../derive_util", version = "0.4" }
