[package]
name = "tuple_routing"
version = "0.4.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "tuple_routing provides a library and interface for tuple-based routing."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[dependencies]
nom = "7.1"

buffertk = { path = "../buffertk", version = "0.11" }
busyrpc = { path = "../busyrpc", version = "0.9" }
indicio = { path = "../indicio", version = "0.9" }
one_two_eight = { path = "../one_two_eight", version = "0.8" }
prototk = { path = "../prototk", version = "0.11" }
prototk_derive = { path = "../prototk_derive", version = "0.11" }
rpc_pb = { path = "../rpc_pb", version = "0.11" }
sync42 = { path = "../sync42", version = "0.13" }
tuple_key = { path = "../tuple_key", version = "0.10" }
utf8path = { path = "../utf8path", version = "0.6" }
zerror = { path = "../zerror", version = "0.7" }
zerror_core = { path = "../zerror_core", version = "0.11" }
zerror_derive = { path = "../zerror_derive", version = "0.6" }

[dev-dependencies]
proptest = "1.0"
