[package]
name = "rpc_pb"
version = "0.12.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "rpc_pb provides prototk definitions for an RPC layer."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[features]
default = ["binaries", "indicio"]

binaries = []
indicio = ["dep:indicio"]

[dependencies]
crc32c = "0.6"

biometrics = { path = "../biometrics", version = "0.11" }
buffertk = { path = "../buffertk", version = "0.12" }
guacamole = { path = "../guacamole", version = "0.11" }
indicio = { path = "../indicio", version = "0.11", optional = true }
one_two_eight = { path = "../one_two_eight", version = "0.9" }
prototk = { path = "../prototk", version = "0.12" }
prototk_derive = { path = "../prototk_derive", version = "0.12" }
utilz = { path = "../utilz", version = "0.6" }
zerror = { path = "../zerror", version = "0.7" }
zerror_core = { path = "../zerror_core", version = "0.12" }
zerror_derive = { path = "../zerror_derive", version = "0.6" }

[[bin]]
name = "rpc-pb-gen-host-id"
path = "src/bin/rpc-pb-gen-host-id.rs"
required-features=["binaries"]

[[example]]
name = "cache"
path = "examples/cache.rs"
required-features=["binaries"]

[[example]]
name = "ping"
path = "examples/ping.rs"
required-features=["binaries"]
