[package]
name = "rpc_pb"
version = "0.1.1"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "rpc_pb provides prototk definitions for an RPC layer."
license = "Apache-2.0"

[dependencies]
biometrics = { path = "../biometrics", version = "0.3" }
buffertk = { path = "../buffertk", version = "0.3" }
guacamole = { path = "../guacamole", version = "0.2" }
one_two_eight = { path = "../one_two_eight", version = "0.1" }
prototk = { path = "../prototk", version = "0.2" }
prototk_derive = { path = "../prototk_derive", version = "0.3" }
utilz = { path = "../utilz", version = "0.1" }
zerror = { path = "../zerror", version = "0.1" }
zerror_core = { path = "../zerror_core", version = "0.2" }
