[package]
name = "scrunch"
version = "0.1.1"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Scrunch provides full-text-searching compression."
license = "Apache-2.0"

[dependencies]
buffertk = { path = "../buffertk", version = "0.5" }
prototk = { path = "../prototk", version = "0.4" }
prototk_derive = { path = "../prototk_derive", version = "0.4" }
zerror_core = { path = "../zerror_core", version = "0.3" }
