[package]
name = "scrunch"
version = "0.7.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "Scrunch provides full-text-searching compression."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[features]
default = ["binaries"]

binaries = []

[dependencies]
buffertk = { path = "../buffertk", version = "0.12" }
prototk = { path = "../prototk", version = "0.11" }
prototk_derive = { path = "../prototk_derive", version = "0.11" }

[dev-dependencies]
proptest = "1.0"

arrrg = { path = "../arrrg", version = "0.7" }
guacamole = { path = "../guacamole", version = "0.11" }
statslicer = { path = "../statslicer", version = "0.8" }

[[bin]]
name = "scrunch"
path = "src/bin/scrunch.rs"
required-features=["binaries"]

[[bin]]
name = "scrunch-inspect"
path = "src/bin/scrunch-inspect.rs"
required-features=["binaries"]

[[bench]]
name = "sparse_bit_vector"
harness = false

[[bench]]
name = "rrr_bit_vector"
harness = false
