[package]
name = "paxos_pb"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "paxos_pb provides protocol buffers for the Paxos prototocol."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[dependencies]
buffertk = { path = "../buffertk", version = "0.6" }
guacamole = { path = "../guacamole", version = "0.6" }
one_two_eight = { path = "../one_two_eight", version = "0.4" }
prototk = { path = "../prototk", version = "0.5" }
prototk_derive = { path = "../prototk_derive", version = "0.5" }
rpc_pb = { path = "../rpc_pb", version = "0.4" }
zerror = { path = "../zerror", version = "0.3" }
zerror_core = { path = "../zerror_core", version = "0.4" }
zerror_derive = { path = "../zerror_derive", version = "0.2" }
