[package]
name = "busybee"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"

biometrics = { path = "../biometrics" }
buffertk = { path = "../buffertk" }
guacamole = { path = "../guacamole", version = "0.1.0" }
hey_listen = { path = "../hey_listen" }
id = { path = "../id" }
prototk = { path = "../prototk" }
prototk_derive = { path = "../prototk_derive" }
util = { path = "../util" }
zerror = { path = "../zerror" }
